<?php
    delete_option('wpec_ps_image_height');
    delete_option('wpec_ps_startSlide');
    delete_option('wpec_ps_pagination');
    delete_option('wpec_ps_dirNav');
    delete_option('wpec_ps_dirNavHide');
    delete_option('wpec_ps_pauseTime');
    delete_option('wpec_ps_pauseOnHover');
    delete_option('wpec_ps_animSpeed');